import { Button, VerticalBox, Slider } from "std-widgets.slint";
import "roboto.ttc";

export component AppWindow inherits Window {
    default-font-family: "Roboto";
    default-font-size: 16px;
    default-font-weight: 400;

    in-out property <string> test: "";

    in-out property <string> message: "Empty Data.";
    in-out property <string> error_message: "";

    callback get_users_me();

    VerticalBox {
        if error_message != "": Text {
            color: red;
            text: error_message;
        }
        if error_message == "": Text {
            text: message;
        }
        Button {
            text: "get users me";
            clicked => {
                get_users_me();
            }
        }

        Text {
            text: "Size: \{Math.round(slider.value)}";
        }

        for i in [100, 200, 300, 400, 500, 600, 700, 800, 900]: Text {
            font-size: Math.round(slider.value) * 1px;
            font-weight: i;
            text: "Test 12345678790";
        }

        slider := Slider {
            minimum: 10;
            maximum: 72;
        }
    }
}
